openapi: 3.0.2
info:
  version: 0.0.9
  title: Regie-backoffice API
  description: "Een open standaard om gegevensuitwisseling tussen regiesystemen en backofficeapplicaties mogelijk te maken.
  Vanuit gemeenten is er behoefte om gegevens tussen regie- en backofficeapplicaties uit te wisselen.
  Omdat hier geen standaard voor is vanuit VNG-Realisatie of het Zorginstituut hebben enkele leveranciers (ZorgNed, Solviteers Software) hier zelf het initiatief toe genomen."

servers:
  - url: https://{environment}.example.com/project-name/api/v1
    description: Testomgeving
    variables:
      environment:
        enum:
          - testen
          - acceptatie
        default: testen

#externalDocs:
#  url: 'https://redmine.solviteers.nl:8443/redmine/projects/wizportaal/wiki/Koppelingen'
#  description: Link to redmine project page

paths:
  /gemeenten/{gemeentecode}/personen/{burgerservicenummer}/aanvragen:
    get:
      summary: Geeft het klantbeeld van een persoon terug
      tags:
        - klantbeeld
      parameters:
        - $ref: '#/components/parameters/gemeentecode'
        - $ref: '#/components/parameters/burgerservicenummer'
        - in: query
          name: regeling
        - in: query
          name: maxeinddatum
        - in: query
          name: sort
      responses:
        '200':
          description: Een collectie aanvragen met beschikkingen en producten
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/aanvraag'

  /gemeenten/{gemeentecode}/personen/{burgerservicenummer}/toewijzingen:
    get:
      summary: Geeft de details van de toewijzing terug op basis van een beschikking
      tags:
        - toewijzingen
      parameters:
        - $ref: '#/components/parameters/gemeentecode'
        - $ref: '#/components/parameters/burgerservicenummer'
        - in: query
          name: beschikkingNummer
          description: iStandaarden BeschikkingNummer
          required: true
          schema:
            type: string
        - in: query
          name: sort
      responses:
        '200':
          description: Een collectie aanvragen met beschikkingen en producten
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/toewijzing'

  /gemeenten/{gemeentecode}/personen/{burgerservicenummer}/toewijzingen/{toewijzingNummer}:
    get:
      summary: Geeft de details van de toewijzing terug
      tags:
        - toewijzingen
      parameters:
        - $ref: '#/components/parameters/gemeentecode'
        - $ref: '#/components/parameters/burgerservicenummer'
        - in: path
          name: toewijzingNummer
          description: iStandaarden ToewijzingNummer
          required: true
          schema:
            type: string
        - in: query
          name: sort
      responses:
        '200':
          description: Een collectie aanvragen met beschikkingen en producten
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/toewijzing'

  /codetabellen/{codetabel}:
    get:
      summary: Geeft de beschikbare collectie van de codetabel terug
      tags:
        - codetabellen
      description: Het opvragen van een collectie van een bepaalde codetabel, bijvoorbeeld productCategorie.
      parameters:
        - in: path
          name: codetabel
          required: true
          schema:
            type: string
            enum: [productCategorie, eenheid, frequentie, redenBeeindiging, redenWijziging]
      responses:
        '200':
          description: Een collectie van de gevraagde codetabel

components:
  parameters:
    gemeentecode:
      in: path
      name: gemeentecode
      description: CBS gemeentecode
      required: true      
      schema:
        $ref: '#/components/schemas/gemeentecode'
    burgerservicenummer:
      name: burgerservicenummer
      in: path
      required: true
      schema:
        $ref: '#/components/schemas/burgerservicenummer'
  schemas:
    gemeentecode:
        type: "string"
        title: "gemeentecode"
        description: "De CBS gemeentecode, Er moeten 4 cijfers aanwezig zijn."
        pattern: "^[0-9]*$"
        maxLength: 4
        minLength: 4
        example: "0216"
    burgerservicenummer:
        type: "string"
        title: "Burgerservicenummer"
        description: "Het burgerservicenummer, bedoeld in artikel 1.1 van de Wet\
          \ algemene bepalingen burgerservicenummer. Alle nummers waarvoor geldt\
          \ dat, indien aangeduid als (s0 s1 s2 s3 s4 s5 s6 s7 s8), het resultaat\
          \ van (9*s0) + (8*s1) + (7*s2) +...+ (2*s7) - (1*s8) deelbaar is door\
          \ elf. Er moeten dus 9 cijfers aanwezig zijn."
        pattern: "^[0-9]*$"
        maxLength: 9
        minLength: 9
        example: "555555021"
    aanvraag:
      type: object
      description: "Een klantvraag die leidt tot een traject met formele of informele ondersteuning"
      properties:
        sleutel:
          type: integer
          format: int32
        regeling:
          $ref: '#/components/schemas/regeling'
        datumAanmelding:
          type: string
          format: date
        datumAanvraag:
          type: string
          format: date
        beschikking:
          $ref: '#/components/schemas/beschikking'
      required:
        - sleutel
        - regeling
        - datumAanmelding
        - datumAanvraag

    regeling:
      type: object
      description: "Omschrijving object"
      properties:
        sleutel:
          type: integer
          format: int32
        omschrijving:
          type: string
      required:
        - sleutel
        - omschrijving

    beschikking:
      type: object
      description: "Omschrijving object"
      properties:
        beschikkingNummer:
          type: integer
          format: int32
        datumAfgifte:
          type: string
          format: date
        toelichting:
          type: string
        beschikteProducten:
          type: array
          items: 
            $ref: '#/components/schemas/beschikteProduct'            
        afgewezenProducten:
          type: array
          items: 
            $ref: '#/components/schemas/afgewezenProduct'  
      required:
        - beschikkingNummer
        - datumAfgifte

    afgewezenProduct:
      type: object
      description: "Omschrijving object"
      properties:
        sleutel:
          type: integer
          format: int32
        product:
          $ref: '#/components/schemas/product'
        productCategorie:
          $ref: '#/components/schemas/productCategorie'
      required:
        - sleutel
        - product

    beschikteProduct:
      type: object
      description: "Omschrijving object"
      properties:
        sleutel:
          type: integer
          format: int32
        product:
          $ref: '#/components/schemas/product'
        productCategorie:
          $ref: '#/components/schemas/productCategorie'
        datumIngangGeldigheid:
          type: string
          format: date
        datumEindeGeldigheid:
          type: string
          format: date
        omvang:
           $ref: '#/components/schemas/omvang'
        leveringsvorm:
          type: string
        leverancier:
          $ref: '#/components/schemas/leverancier'
        toelichting:
          type: string
        toewijzing:
          $ref: '#/components/schemas/toewijzing'
      required:
        - sleutel
        - product
        - datumIngangGeldigheid
        - omvang

    toewijzing:
      type: object
      description: "Omschrijving object"
      properties:
        toewijzingNummer:
          type: integer
          format: int32
        toewijzingsDatumTijd:
          type: string
          format: date-time
        toewijzingIngangsdatum:
          type: string
          format: date
        toewijzingEinddatum:
          type: string
          format: date
        leverancier:
          $ref: '#/components/schemas/leverancier'
        referentieAanbieder:
          type: string
          maxLength: 36
        redenWijziging:
          type: string
          minLength: 2
          maxLength: 2
        levering:
          type: array
          items: 
            $ref: '#/components/schemas/levering'
      required:
        - toewijzingNummer
        - toewijzingsDatumTijd
        - toewijzingIngangsdatum
        - leverancier

    product:
      type: object
      description: "Omschrijving object"
      properties:
        sleutel:
          type: integer
          format: int32
        productCode:
          type: string
          minLength: 1
          maxLength: 5
        omschrijving:
          type: string
      required:
        - sleutel
        - omschrijving

    productCategorie:
      type: object
      description: "Omschrijving object"
      properties:
        code:
          type: string
          minLength: 2
          maxLength: 2
        omschrijving:
          type: string
      required:
        - code
        - omschrijving

    omvang:
      type: object
      description: "Omschrijving object"
      properties:
        volume:
          type: integer
          format: int32
        eenheid:
          $ref: '#/components/schemas/eenheid'
        frequentie:
          $ref: '#/components/schemas/frequentie'
      required:
        - volume
        - eenheid
        - frequentie

    eenheid:
      type: object
      description: "Omschrijving object"
      properties:
        code:
          type: string
          minLength: 2
          maxLength: 2
        omschrijving:
          type: string
      required:
        - code
        - omschrijving

    frequentie:
      type: object
      description: "Omschrijving object"
      properties:
        code:
          type: string
          minLength: 1
          maxLength: 1
        omschrijving:
          type: string
      required:
        - code
        - omschrijving

    leverancier:
      type: object
      description: "Omschrijving object"
      properties:
        sleutel:
          type: integer
          format: int32
        agbcode:
          type: string
          minLength: 8
          maxLength: 8
        kvk:
          type: string
        omschrijving:
          type: string
      required:
      - sleutel
      - omschrijving      
      
    levering:
      type: object
      description: "Omschrijving object"
      properties:
        begindatum:
          type: string
          format: date
        einddatum:
          type: string
          format: date
        redenBeeindiging:
          $ref: '#/components/schemas/redenBeeindiging'
      required:
      - begindatum

    redenBeeindiging:
      type: object
      description: "Omschrijving object"
      properties:
        code:
          type: string
          minLength: 2
          maxLength: 2
        omschrijving:
          type: string
      required:
        - code
        - omschrijving

    redenWijziging:
      type: object
      description: "Omschrijving object"
      properties:
        code:
          type: string
          minLength: 2
          maxLength: 2
        omschrijving:
          type: string
      required:
        - code
        - omschrijving