openapi: '3.0.0'
info:
  title: Generieke componenten voor Haal Centraal APIs
  version: '1.0'
components:
  schemas:
    Foutbericht:
      type: object
      description: Terugmelding bij een fout. JSON representatie in lijn met [RFC7807](https://tools.ietf.org/html/rfc7807).
      properties:
        type:
          type: string
          format: uri
          description: Link naar meer informatie over deze fout
        title:
          type: string
          description: Beschrijving van de fout
        status:
          type: integer
          description: Http status code
        detail:
          type: string
          description: Details over de fout
        instance:
          type: string
          format: uri
          description: Uri van de aanroep die de fout heeft veroorzaakt
        code:
          type: string
          description: Systeemcode die het type fout aangeeft
          minLength: 1
